### ISSUE TITLE
Server neupdatuje LastChanged v Tasku při změně timu

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#20]
Když je změněn time, tak není updatován LastChanged na současné datum a proto se změny projeví pouze na Daemonech, kteří tento task nemají už lokálně stažený.

Nebylo testováno jestli LastChanged je updatováno při změně TaskLocationu, Credentials a další, ale je nutné aby se updatovalo pokud cokoliv společného s taskem se má projevit na daemonovi

**Comment by donutX3** [comment]
Uz se lastchanged meni
