### ISSUE TITLE
Settings soubor pro Server

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#22]
Pro připojení k MySQL využívá server .ini soubor, ale v shared knihovně by mohl být vytvořen settings soubor, který by server používal.

**Comment by donutX3** [comment]
Běžně se na tyhle věci prostě používá Web.config

**Comment by lukx1** [comment]
Na specifické implementaci nezáleží. Tento issue jen znázorňuje nejasnost využívání .ini souboru a doporučuje odstranit reference na něj a nahradit jej jiným, nejlépe settingovým, souborem.
