### ISSUE TITLE
Daemon by měl poskytovat jméno počítače

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#24]
Na serveru by měl být přidán sloupec a měl by být upraven introduction message aby toto obsahoval. Samozřejmě že i stránka Daemons by tyto údaje měla obsahovat.

Jméno

**Comment by donutX3** [comment]
Pridano jak na serveru tak i kdyz daemon zpetne odesila IntroMessage. Pro ziskani jmena pocitace pouzivat Environment.MachineName
