### ISSUE TITLE
SmartBackup file not found crash

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#3]
SmartBackup crashne když část cesti v CreateFullBackupInfo neexistuje

`System.IO.DirectoryNotFoundException: Část cesty C:\Users\TestUser\Desktop\Pictures nebyla nalezena.`
Stack Trace

`"   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   v System.IO.FileSystemEnumerableIterator`1.CommonInit()\r\n   v System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)\r\n   v System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)\r\n   v System.IO.DirectoryInfo.GetFiles()\r\n   v Daemon.Backups.SmartBackupInfo.CreateFullBackupInfo(String path) v X:\\ZPR\\Backupper\\Core\\Daemon\\Daemon\\Backups\\SmartBackupInfo.cs:řádek 30\r\n   v Daemon.Backups.SmartBackup.StartBackup() v X:\\ZPR\\Backupper\\Core\\Daemon\\Daemon\\Backups\\SmartBackup.cs:řádek 30\r\n   v Daemon.TaskHandler.<>c__DisplayClass7_0.<CreateTimedBackup>b__0(Object e) v X:\\ZPR\\Backupper\\Core\\Daemon\\Daemon\\TaskHandler.cs:řádek 102\r\n   v System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)\r\n   v System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   v System.Threading.TimerQueueTimer.CallCallback()\r\n   v System.Threading.TimerQueueTimer.Fire()\r\n   v System.Threading.TimerQueue.FireNextTimers()\r\n   v System.Threading.TimerQueue.AppDomainTimerCallback()"`

**Comment by Nightraw** [comment]
Such stupid, much closed.
