### ISSUE TITLE
Incremental nepozná změněný soubor

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#31]
Incremental backup nepozná že soubor byl změněn a nezkopíruje ho.
Otestováno unit testem

Proces:
```
Záloha 1
Source/A.Dum -> Dest/A.Dum
----
Source/A.Dum byl upraven + prodleva 1s
Záloha 2
Source/A.Dum -X-> Dest/A.Dum
Soubor nebyl zkopírován
```

**Comment by Nightraw** [comment]
To moje dělá podle date modified, myslím že tam je nejmenší interval minuta, který i dělá smysl protože jsem nepředpokládal zálohu každou sekundu.

**Comment by Nightraw** [comment]
Už pozná, chyba byla porovnávání Datetimu stejných FileInfo a pak také odchylka v milisekundách co nerozpoznala že to je stejný file.
