### ISSUE TITLE
Differential nepozná upravený soubor

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#32]
Stejný případ jako [Issue 31](https://github.com/lukx1/Backupper/issues/31l).
Otestováno unit testem

Chyba bude v SmartBackupInfo řádek 60
`item.destination == file.destination && item.lastDateModified == file.lastDateModified`
kde item.lastDateModified == file.lastDateModified je vždy true

Proces:

Záloha 1
Source/A.Dum -> Dest/A.Dum
----
Source/A.Dum byl upraven + prodleva 1s
Source/X.Dum byl vytvořen
Záloha 2
Source/X.Dum -> Dest/X.Dum (úspěšné)
Source/A.Dum -X-> Dest/A.Dum
Soubor nebyl zkopírován

**Comment by Nightraw** [comment]
ok, kouknu dnes na ten bug z lastDateModified

**Comment by Nightraw** [comment]
Už pozná, chyba byla porovnávání Datetimu stejných FileInfo a pak také odchylka v milisekundách co nerozpoznala že to je stejný file.
